"""create api keys, idempotency keys, request logs

Revision ID: 3afecb7593b3
Revises: 7f5972522c72
Create Date: 2026-08-31 02:50:37.219238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3afecb7593b3'
down_revision: Union[str, None] = '7f5972522c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_api_keys',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_api_keys_application_id'), 'application_api_keys', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_api_keys_key_prefix'), 'application_api_keys', ['key_prefix'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_application_id'), 'idempotency_keys', ['application_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('request_logs',
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retrieval_strategy', sa.String(length=20), nullable=True),
    sa.Column('vector_backend', sa.String(length=20), nullable=True),
    sa.Column('error_detail', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_application_id'), 'request_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_request_logs_created_at'), 'request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_request_id'), 'request_logs', ['request_id'], unique=False)
    # NOTE: autogenerate also detected `memory_vectors_verify_pgvector_g1`
    # (and its indexes) as "removed" — that table is NOT part of the
    # declared SQLAlchemy models. It's a per-application vector table
    # created dynamically by PgvectorAdapter.provision() at runtime (see
    # docs/04-vector-store-adapters.md's documented Alembic exception for
    # data-driven per-application storage). The DROP TABLE Alembic wanted
    # to generate here has been deliberately removed — never let autogenerate
    # touch memory_vectors_* tables.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_request_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_created_at'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_application_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_application_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_application_api_keys_key_prefix'), table_name='application_api_keys')
    op.drop_index(op.f('ix_application_api_keys_application_id'), table_name='application_api_keys')
    op.drop_table('application_api_keys')
    # ### end Alembic commands ###
