"""add judge llm config to applications

Revision ID: 5bc884cf5881
Revises: 3afecb7593b3
Create Date: 2026-09-02 16:39:34.893775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc884cf5881'
down_revision: Union[str, None] = '3afecb7593b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also detected `memory_vectors_verify_pgvector_g1`
    # as "removed" — that table is NOT part of the declared SQLAlchemy
    # models. It's a per-application vector table created dynamically by
    # PgvectorAdapter.provision() at runtime (see
    # docs/04-vector-store-adapters.md's documented Alembic exception).
    # The DROP TABLE Alembic wanted to generate here has been deliberately
    # removed — never let autogenerate touch memory_vectors_* tables.
    op.add_column('applications', sa.Column('judge_llm_provider', sa.String(length=20), nullable=True))
    op.add_column('applications', sa.Column('judge_llm_model', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('judge_llm_base_url', sa.String(length=255), nullable=True))
    op.add_column('applications', sa.Column('judge_llm_api_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'judge_llm_api_key_encrypted')
    op.drop_column('applications', 'judge_llm_base_url')
    op.drop_column('applications', 'judge_llm_model')
    op.drop_column('applications', 'judge_llm_provider')
    # ### end Alembic commands ###
