"""create memories table

Revision ID: 7f5972522c72
Revises: d8b5ebe328fb
Create Date: 2026-08-31 02:26:10.881584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f5972522c72'
down_revision: Union[str, None] = 'd8b5ebe328fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('vector_backend_generation', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['memories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_application_id'), 'memories', ['application_id'], unique=False)
    op.create_index(op.f('ix_memories_namespace'), 'memories', ['namespace'], unique=False)
    op.create_index(op.f('ix_memories_subject_id'), 'memories', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_subject_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_namespace'), table_name='memories')
    op.drop_index(op.f('ix_memories_application_id'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
